services:
  frontend:
    build:
      context: web
    image: web:latest
    environment:
      - VITE_API_URL=${VITE_API_URL}
    restart: unless-stopped
    expose:
      - 3000
    depends_on:
      - backend
    networks:
      - dokploy-network

  backend:
    build:
      context: api
    image: api:latest
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
      - BOT_TOKEN=${BOT_TOKEN}
    restart: unless-stopped
    expose:
      - 8080
    depends_on:
      - database
    networks:
      - dokploy-network
  
  bot:
    build:
      context: bot
    image: bot:latest
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    restart: unless-stopped
    networks:
      - dokploy-network

  database:
    image: postgres:15-bullseye
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
    ports:
      - 5432:5432
    networks:
      - dokploy-network
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

networks:
  dokploy-network:
    external: true